version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./config.ini:/app/config.ini
      - ./vm/vm_passwords.yml:/app/vm/vm_passwords.yml
      - ./pdf:/app/pdf
#    ports:
#      - "3326:3326"
