---
- name: Setup rclone and mount pdf-cloud
  hosts: all
  become: yes

  vars:
    rclone_config_dir: "/root/.config/rclone"
    rclone_config_file: "{{ rclone_config_dir }}/rclone.conf"
    mount_dir: "/Volumes/pdf"

  tasks:
    - name: Get the current user on the target machine
      shell: whoami
      register: whoami_output
      become: no

    - name: Set default user from the output of whoami
      set_fact:
        default_user: "{{ whoami_output.stdout }}"

    - name: Ensure rclone config directory exists
      file:
        path: "{{ rclone_config_dir }}"
        state: directory
        mode: '0755'

    - name: Include vm_passwords.yml
      include_vars:
        file: vm_passwords.yml
        name: vm_passwords

    - name: Show rclone_config_file contents
      debug:
        var: rclone_config_file
      become: no  # Run as the default user

    - name: Add configuration to rclone.conf
      blockinfile:
        path: "{{ rclone_config_file }}"
        create: yes
        block: |
          [pdf-cloud]
          type = s3
          provider = Other
          access_key_id = {{ vm_passwords.pdf_s3_access_key_id }}
          secret_access_key = {{ vm_passwords.pdf_s3_secret_access_key }}
          endpoint = {{ vm_passwords.pdf_s3_pdf_endpoint }}
          acl = private


    - name: Check if rclone is running
      shell: pgrep rclone
      register: rclone_pid
      ignore_errors: yes

    - name: Kill existing rclone process
      shell: kill {{ rclone_pid.stdout }}
      when: rclone_pid.rc == 0

    - name: Unmount the directory if mounted
      shell: umount "{{ mount_dir }}"
      ignore_errors: yes


    - name: Check if mount directory exists
      stat:
        path: "{{ mount_dir }}"
      register: mount_dir_stat

    - name: Create mount directory
      file:
        path: "{{ mount_dir }}"
        state: directory
        mode: '0755'
      when: not mount_dir_stat.stat.exists

    - name: Mount pdf-cloud using rclone with user write permissions and friendly file creation
      shell: |
        rclone mount pdf-cloud:citations-finder-pdfs {{ mount_dir }} --default-permissions --allow-other --umask 002 --file-perms 0666 --dir-perms 0777 --uid $(id -u {{default_user}}) --gid $(id -g {{default_user}}) --daemon
      args:
        creates: "{{ mount_dir }}/something"

    - name: Create symbolic link for /opt/citations_finder/pdf
      file:
        src: /Volumes/pdf/pdf
        dest: /opt/citations_finder/pdf
        state: link
        force: yes
